<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="[11.3.22]" />
    <PackageReference Include="Avalonia.Desktop" Version="[11.3.22]" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="[11.3.22]" />
    <ProjectReference Include="..\LegACEy.Client.Demo\LegACEy.Client.Demo.csproj" />
    <ProjectReference Include="..\LegACEy.Client.Themes\LegACEy.Client.Themes.csproj" />
  </ItemGroup>
</Project>
