<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="[11.3.22]" />
    <PackageReference Include="Avalonia.Headless" Version="[11.3.22]" />
    <PackageReference Include="Avalonia.Skia" Version="[11.3.22]" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="[11.3.22]" />
  </ItemGroup>

</Project>
